apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mon-app
  template:
    metadata:
      labels:
        app: mon-app
    spec:
      containers:
      - name: mon-app
        image: harbor.local/library/mon-app:9cc62ea455800364f52962358ef5e51ab4bc43e1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
      - name: harbor-registry-secret
