apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mon-app
  template:
    metadata:
      labels:
        app: mon-app
    spec:
      containers:
      - name: mon-app
        image: harbor.local/library/mon-app:cfebd18463864c3298e1695b8e26c1cc97843a2b
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
      - name: harbor-registry-secret
