apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jaeger-ingress
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`jaeger.local`)
      kind: Rule
      services:
        - name: jaeger
          port: 16686